name: feedback-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - mystmd
  - jupyterlab
  - jupyterlab-myst
  - numpy
  - matplotlib
  - pandas
  - xarray
  - xesmf
  - cartopy
  - dask
  - dask-gateway
  - tqdm
  - intake
  - intake-esm
  - fsspec
  - cftime
  - nc-time-axis
  - gcsfs
  - s3fs
  - h5netcdf
  - pip
  - pip:
    - git+https://github.com/brian-rose/climkern.git@stream  # a modified version that streams the kernel data
